# Base
seed: 9999

# LLM model
supervisor_model: gpt-5-nano
task_model: gpt-5-nano
vllm_url: http://0.0.0.0:8000     # Used only when using vllm.

# Simulation environment
agent_test_data: hospital_data/primary/agent_data
fhir_url: http://localhost:8080/fhir
integration_with_fhir: False

# Hospital environment
booking_days_before_simulation: 3       # Number of days before the simulation date when appointment booking can start
fhir_max_connection_retries: 5          # Maximum number of retry attempts when retrieving data from the FHIR server
schedule_cancellation_prob: 0.05
request_early_schedule_prob: 0.1

# Simulation conditions
outpatient_intake:
    use_supervisor: False
    intake_max_inference: 5
schedule_task:
    scheduling_strategy: tool_calling   # ['llm', 'tool_calling']