# LLM model
model: gpt-4o-mini # gemini-2.5-flash-preview-05-20

# Agent test data and converted FHIR data folder
agent_test_data: synthetic_data/hospital_easy_small/agent_data
fhir_data: synthetic_data/hospital_easy_small/fhir_data

# Prompt paths
department_task:
    system_prompt: asset/prompts/department_system.txt
    user_prompt: asset/prompts/department_user.txt
schedule_task:
    system_prompt: asset/prompts/schedule_system.txt
    user_prompt: asset/prompts/schedule_user.txt
fhir_resource_task:
    system_prompt: asset/prompts/fhir_resource_system.txt
    user_prompt: asset/prompts/fhir_resource_user.txt