# Base
seed: 9999

# FHIR server url
fhir_url: http://localhost:8080/fhir

# Data configs
create_data_path: ./data  #  Path of data to create. We can set it to individual JSON files or a directory containing multiple JSON files.