# Base
seed: 9999

# FHIR server url
fhir_url: http://localhost:8080/fhir

# Data configs
project: ./synthetic_data/
data_name: hospital_easy
hospital_data:
    hospital_n: 10000
    interval_hour: 0.5
    start_hour:
        min: 6
        max: 8
    end_hour:
        min: 18
        max: 20
    department_per_hospital:
        min: 2
        max: 5    
    doctor_per_department:
        min: 1
        max: 5
    doctor_has_schedule_prob: 0.3
    schedule_coverage_ratio:
        min: 0.01
        max: 0.2

